language: node_js

compiler: gcc
sudo: false

os:
- linux
- osx

env:
  global:
    - secure: JyNJe+dEpj5feig+xwuopgJZGfih0gzOHj+uh9iLO0LgIILVwUzeUNkMZpaT/ydsLBLTdSTKary3mts2oE878lQImi1va0hB4QKKtf+P0kNmeYaEDc8U1dLOv/0d0veMQD3ig8JzajcU5s6znhPOi/PnNTY3aGSnvE3UNr/9N5sz0Gxw/nfnanK3VcRbDqkDw/f3lUj30YLc0xR4e1HXNS+bqSLRg8pgYHtwModjsX5Y1t3BQOsB4fZu/Joo3Hz5jr6uFHECcVTwW5LPtfNq+96iTdEOk+dU03uZCyr++vBqX0/8acOsY4heFeCKpQDSPxQ/tTBtEcRTRFME4FSCxc0oh9VorgkAjszSTL6Ff64rxEfRX4rqkWgqQaaeA1e8sgJENydFNvjYt1IoSTzdYvof7EPk3kk7rbZmTdaygqt2F2KDzjFC5z4jHYk04cQSm5jIrIVQfaBJ83SFm/cH6Q+totQ48OAJxFz4VfGG5m8Tl1gBjwhAwl3+9D2m2SdebxNjCAJ8My+JlHx1D6DTR+/ir/Wd9tppZc/L2jRhY/qNz5fq+OF+yzM2CQNBjMOOrYoSbEz+rCyaXg/EYAFn5KnA0D6dRKvdiCnbhrE9BlfzcTUVUi9rAXZ03Bl++NU9//ECe30sU/vjpHPiQs280eJkYphoknjpWuZp8FEu0c0=

node_js:
# support latest Nodejs LTS version
- '10'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

sudo: false

before_install:
- if [ "$TRAVIS_NODE_VERSION" = "0.8" ]; then npm install -g npm@2.7.3; fi;
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CC="gcc-4.8";
    export CXX="g++-4.8";
    export LINK="gcc-4.8";
    export LINKXX="g++-4.8";
  fi
- nvm --version
- node --version
- npm --version
- gcc --version
- g++ --version

before_script:
# figure out if we should publish
- echo $TRAVIS_BRANCH
- echo `git describe --tags --always HEAD`
- PUBLISH_BINARY=false
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` || ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then PUBLISH_BINARY=true; fi;
- echo "Publishing binaries? ->" $PUBLISH_BINARY

install:
- npm install --build-from-source

script:
- npm test
- if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp rebuild package && node-pre-gyp-github publish --release; fi;

#cache:
#  directories:
#    - $HOME/.node-gyp
#    - $HOME/.npm
#    - node_modules
