blank_issues_enabled: false
contact_links:
  - name: Issues when using Botpress
    url: https://github.com/botpress/botpress
    about: If you're experiencing issues when using Botpress but you're not sure about the nature of the issue, please report the issue on the main Botpress repo.
  - name: Ask a question
    url: https://forum.botpress.com/
    about: If you have a "How do I?" question please ask in the forum https://forum.botpress.com
