name: Setup E2E
description: Setup E2E NLU Usage

inputs:
  lang_server_dim:
    description: 'Dimension in which to run the language server'
    required: false
    type: 'string'
    default: '25'

  lang_server_lang:
    description: 'Language to download in the language server'
    required: false
    type: 'string'
    default: 'en'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
    - name: Fetch Node Packages
      shell: bash
      run: yarn
    - name: Build
      shell: bash
      run: yarn build
    - name: package
      shell: bash
      run: yarn package --linux
    - name: Rename binary
      id: rename_binary
      shell: bash
      run: |
        bin_original_name=$(node -e "console.log(require('./scripts/utils/binary').getFileName())")
        echo "Moving ./dist/$bin_original_name to ./nlu ..."
        mv ./dist/$bin_original_name ./nlu
    - name: Download language models
      shell: bash
      run: ./nlu lang download --lang ${{ inputs.lang_server_lang }} --dim ${{ inputs.lang_server_dim }}
    - name: Start Language Server
      shell: bash
      run: |
        ./nlu lang --dim ${{ inputs.lang_server_dim }} &
        echo "Lang Server started on pid $!"
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
