name: Binary
on: [pull_request]
jobs:
  nlu:
    name: Try out binary executable file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'
      - name: Fetch Node Packages
        run: |
          yarn --verbose
      - name: Build
        run: |
          yarn build
      - name: package
        run: |
          yarn package --linux
      - name: Rename binary
        id: rename_binary
        run: |
          bin_original_name=$(node -e "console.log(require('./scripts/utils/binary').getFileName())")
          echo "Moving ./dist/$bin_original_name to ./nlu ..."
          mv ./dist/$bin_original_name ./nlu
      - name: Download language models
        run: |
          ./nlu download --lang en --dim 25
      - name: Run Regression Test
        run: |
          ./nlu lang --dim 25 &
          sleep 15s && ./nlu --doc false --verbose 0 --ducklingEnabled false --languageURL http://localhost:3100 &
          sleep 25s && BITFAN_LANG='en' yarn e2e -t "bpds-intent" -k
