name: Codestyle
on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  run_prettier:
    name: Run Prettier on codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
      - name: Install Dependencies
        run: |
          yarn
      - name: Run Prettier
        run: |
          yarn prettier
  eslint:
    name: Run ESLint on codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
      - name: Install Dependencies
        run: |
          yarn
      - name: Run ESLint
        run: |
          yarn eslint
