name: Docker
on:
  push:
    branches:
      - 'master'
      - 'next'
      - 'cloud'
    tags:
      - v*
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: botpress/gh-actions/build/docker@v2
        with:
          repository: nlu
