name: Docker
on:
  push: {}
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  nlu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: botpress/gh-actions/build/docker@v2
        with:
          repository: nlu
