name: E2E
on: [pull_request]
jobs:
  fs:
    name: file system
    runs-on: ubuntu-latest
    services:
      duckling:
        image: rasa/duckling
        ports:
          - 8000:8000
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup E2E
        uses: ./.github/actions/setup-e2e
      - name: Start NLU Server
        run: |
          ./nlu \
            --log-level "critical" \
            --ducklingURL http://localhost:8000 \
            --languageURL http://localhost:3100 \
            --modelTransferEnabled \
            --port 3200  &
          nlu_pid=$!
          echo "NLU Server started on pid $nlu_pid"
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'
      - name: Run Tests
        run: |
          yarn e2e --nlu-endpoint http://localhost:3200
  db:
    name: database
    runs-on: ubuntu-latest
    services:
      duckling:
        image: rasa/duckling
        ports:
          - 8000:8000
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_DB: botpress-nlu-1
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup E2E
        uses: ./.github/actions/setup-e2e
      - name: Start NLU Server
        run: |
          ./nlu \
            --log-level "critical" \
            --ducklingURL http://localhost:8000 \
            --languageURL http://localhost:3100 \
            --modelTransferEnabled \
            --port 3201 \
            --dbURL postgres://postgres:postgres@localhost:5432/botpress-nlu-1 & \
          nlu_pid=$!
          echo "NLU Server started on pid $nlu_pid"
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'
      - name: Run Tests
        run: |
          yarn e2e --nlu-endpoint http://localhost:3201
  cluster:
    name: cluster
    runs-on: ubuntu-latest
    services:
      duckling:
        image: rasa/duckling
        ports:
          - 8000:8000
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_DB: botpress-nlu-2
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup E2E
        uses: ./.github/actions/setup-e2e
      - name: Start First NLU Server on port 3202
        run: |
          ./nlu \
            --maxTraining 0 \
            --maxLinting 0 \
            --log-level "critical" \
            --ducklingURL http://localhost:8000 \
            --languageURL http://localhost:3100 \
            --modelTransferEnabled \
            --port 3202 \
            --dbURL postgres://postgres:postgres@localhost:5432/botpress-nlu-2 & \
          nlu_pid1=$!
          echo "NLU Server started on pid $nlu_pid1"
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'
      - name: Start Second NLU Server on port 3203
        run: |
          ./nlu \
            --log-level "critical" \
            --ducklingURL http://localhost:8000 \
            --languageURL http://localhost:3100 \
            --port 3203 \
            --dbURL postgres://postgres:postgres@localhost:5432/botpress-nlu-2 & \
          nlu_pid2=$!
          echo "NLU Server started on pid $nlu_pid2"
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'
      - name: Run Tests
        run: |
          yarn e2e --nlu-endpoint http://localhost:3202
