name: Release
on: push
jobs:
  release_bin:
    name: Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Fetch Node Packages
        run: |
          yarn --verbose
      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
      - name: 'Echo Latest Tag'
        id: echo_tag
        run: |
          echo ${{ steps.previoustag.outputs.tag }}
      # - name: Release
      #   run: |
      #     GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} yarn cmd release
