name: Release
on: push
jobs:
  release_bin:
    name: Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Git Unshalow
        run: git fetch --prune --unshallow
      - name: Fetch Node Packages
        run: |
          yarn --verbose
      - name: Get Previous Tag
        id: previous_tag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
      - name: Get Current Version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Validate Semver
        id: validate_semver
        run: |
          valid_latest_tag=$(node ./node_modules/semver/bin/semver.js ${{ steps.previous_tag.outputs.tag }})
          valid_current_version=$(node ./node_modules/semver/bin/semver.js ${{ steps.extract_version.outputs.version }})
          echo '::set-output name=valid_latest_tag::$valid_latest_tag'
          echo '::set-output name=valid_current_version::$valid_current_version'
      - name: 'Release'
        if: ${{ steps.validate_semver.outputs.valid_latest_tag != steps.validate_semver.outputs.valid_current_version }}
        run: |
          echo ${{ steps.validate_semver.outputs.valid_latest_tag }}
          echo ${{ steps.validate_semver.outputs.valid_current_version }}
          echo ${{ steps.validate_semver.outputs.valid_latest_tag != steps.validate_semver.outputs.valid_current_version }}
      # - name: Build
      #   run: |
      #     yarn build
      # - name: Package
      #   run: |
      #     yarn package
      # - name: Release
      #   run: |
      #     GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} yarn cmd release
