name: Release
on: push
jobs:
  release_bin:
    name: Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Fetch Node Packages
        run: |
          yarn --verbose
      - name: Release
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} yarn cmd release
