name: Tests
on: [pull_request]
jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build
        run: |
          cp -r build/tests/* .
          docker-compose build
      - name: Run tests
        run: |
          docker-compose up --exit-code-from botpress
