name: Tests
on: [pull_request]
jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Fetch Node Packages
        run: |
          yarn --verbose
      - name: Build
        run: |
          yarn build
      - name: Run tests
        run: |
          yarn test
